### PR TITLE
Add completer option and forward as option to readline

### PR DESCRIPTION
**Pull request by 131**

### CODE REVIEW

**Comment by isaacs** [comment]
Good idea, but needs a test.

**Comment by 131** [comment]
I wrote a simple test for completion to readline.
In the child, i react to a very simple completion event the master tap test just need to press the "tab" key.
Very simple, very efficient.

And not working
I spend 1 hour trying to understand & send the proper "whaterver key just send "tab" to the other side" key, with no success.

Feel free to take a look, i'm stuck here

    // this is NOT sending TAB key to underlying child
    write('\t'); 
    //nor this
    write('\x1b[I');

**Comment by 131** [comment]
2 years later, i end up understanding that sending control chars (e.g. TAB) require a tty, not a pipe.
Is it ok now ?

**Comment by 131** [comment]
Hi isaacs !
I know how busy you are, maybe you don't want to touch this module anymore, do you prefer that I publish read myself (with another name) to access this feature ?

Thank you very much !

**Comment by wraithgar** [comment]
Rebased in https://github.com/npm/read/pull/51

**Comment by 131** [comment]
YES ! Thanks.

**Pull request closed without merging**
